// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnuydoujbrpfhohsxndz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBudXlkb3VqYnJwZmhvaHN4bmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4ODY0NTksImV4cCI6MjA4NjQ2MjQ1OX0.Mr9s4lObDXWp6p3TOVNcT6VZCIC0twGgxNXwQTJT1X8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});